services:
  postgres-db:
    image: postgres:15
    container_name: pg-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s

  worker:
    build: ./worker
    container_name: worker-app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - DB_HOST=postgres-db
      - JUDGE_DATA_DIR=${JUDGE_DATA_DIR} # for compiling with docker on host machine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JUDGE_DATA_DIR}:/data # read in and out files
    depends_on:
      postgres-db:
        condition: service_healthy
  
  syncer:
    build: ./worker
    container_name: worker-syncer
    profiles: ["tools"]
    command: ["/app/syncer"]
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - DB_HOST=postgres-db
      - DATA_DIR=/data
    volumes:
      - ${JUDGE_DATA_DIR}:/data
    depends_on:
      postgres-db:
        condition: service_healthy
  
  c-judger:
    build: ./images/c
    image: c-judger
    profiles: ["build-only"]

  cpp-judger:
    build: ./images/cpp
    image: cpp-judger
    profiles: ["build-only"]

  python-judger:
    build: ./images/python
    image: python-judger
    profiles: ["build-only"]

  java-judger:
    build: ./images/java
    image: java-judger
    profiles: ["build-only"]
volumes:
  pgdata: